language: python
python:
    - "3.5"
    - "3.6"
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y tmux build-essential libssl-dev libffi-dev python3-dev sshpass openssl
    - sudo pip install virtualenv
install:
    - python setup.py install
script:
    - python setup.py test
