language: python
python:
    - "3.5"
    - "3.6"
install:
    - sudo apt-get install -y tmux build-essential libssl-dev libffi-dev python3-dev sshpass virtualenv openssl
    - python setup.py install
script:
    - python setup.py test
